esphome:
  name: nodemcu
  friendly_name: NodeMCU

esp8266:
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encrypt_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu Fallback Hotspot"
    password: !secret wifi_ap_password

captive_portal:

external_components:
    - source:
        type: local
        path: components

sensor:
  - platform: empty_sensor
    pin: D2
    name: Empty sensor
